apiVersion: apps/v1                 # API version used for creating DaemonSet
kind: DaemonSet                     # We're defining a DaemonSet

metadata:
  name: jenkins-daemonset          # Name of the DaemonSet
  labels:
    app: jenkins-daemon            # Label to identify this DaemonSet

spec:
  selector:
    matchLabels:
      app: jenkins-daemon          # Tells DaemonSet which pods it will manage (those with this label)

  template:                         # Pod template for each node
    metadata:
      labels:
        app: jenkins-daemon        # Pod created will carry this label

    spec:
      containers:
        - name: jenkins            # Name of the container
          image: jenkins/jenkins:latest   # Jenkins Docker image to run in each pod
          ports:
            - containerPort: 8080  # Jenkins will run on port 8080 inside the container
